### ISSUE TITLE
Why is Mum used with minus?

### ISSUE THREAD

**Issue by thomasahle** [tommyettinger/waterhash#1]
I find it very interesting that the "multiply and mix" operation uses minus for the mixing in line
https://github.com/tommyettinger/waterhash/blob/49f5cf0b63b95b112b45c054afabb8d9c904ce3a/waterhash.h#L17
Is this just an arbitrary choice? Or have you seen this elsewhere? Or written about why you chose it?

**Comment by tommyettinger** [comment]
To be perfectly honest, it's because SMHasher found anomalies or had failed tests with addition and xor, and for some reason didn't have problems with subtraction. Trial and error, where there aren't that many trials possible (`+, -, ^`, but then what?) In all cases but xor, the result is an imperfect mix, but mum here can't be a perfect mix (an invertible function) because it takes in more bits than it intends to produce, if I remember correctly. I'd seen subtracted right-shift somewhere before; I don't know where, though it wasn't in the context of a "mathematically clean" function.

WaterHash is really practically scraping the edge of what SMHasher finds acceptable in a hash, though it does narrowly get through it and does so with decent speed. XXH3 is incredible and quite a bit faster, but is a much larger code base. I'm guessing most people who are looking at WaterHash are not also looking at AES-based options, but if using a setup that can take advantage of hardware acceleration for AES operations, that will probably be fastest. I think WaterHash is mostly interesting because it's somewhat small and still passes tests with good-enough performance; wyhash has changed since I made my WaterHash edits, and it may be faster or slower now.

**Comment by thomasahle** [comment]
That's fascinating. I thought this for sure couldn't make a difference in the results, so it would have to be for performance somehow. Thank you for the comprehensive explanation!
